@BibsAPI_HostAddress = http://localhost:5246

# GET {{BibsAPI_HostAddress}}/weatherforecast/
# Accept: application/json

###
GET {{BibsAPI_HostAddress}}/clubs/GetClubs
Accept: application/json
