version: '3.8'

networks:
    dockerapi-dev:
        driver: bridge

services:
    # Postgres DB
    postgres_image:
        container_name: 'postgres'
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: '4y7sV96vA9wv46VR'
            POSTGRES_USER: 'postgres_user'
            POSTGRES_DB: 'bouldersDb'
            PGDATA: /data/postgres
        #restart: always
        healthcheck:
            #test: ["CMD-SHELL", "pg_isready", "-d", "bouldersDb"]
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            timeout: 60s
            retries: 5
            #start_period: 80s 
        volumes:
            - postgres:/data/postgres
        networks:
            - dockerapi-dev
        ports:
            - 5432:5432
    # API
    app-api:
        image: BibsAPI:latest
        container_name: BibsAPI
        #platform: linux/amd64
        depends_on: 
            postgres_image:
                condition: service_healthy
        links:
            - postgres_image
        environment:
            - ASPNETCORE_ENVIRONMENT=Release
            - PostgresSettings__ConnectionString=host=host.docker.internal;port=5432;userid=postgres_user;database=bouldersDb;Password=4y7sV96vA9wv46VR
        ports:
            - '5088:80'
        networks:
            - dockerapi-dev
volumes:
    postgres: